"use client";

import { CheckCircleOutlined, RobotOutlined, WarningOutlined } from "@ant-design/icons";
import { Alert, Button, Tag } from "antd";

import { Insight, Sentiment } from "@/lib/types";

const SENTIMENT_COLOR: Record<Sentiment, string> = {
  positive: "green",
  neutral: "default",
  negative: "red",
};

export function InsightPanel({
  insight,
  onRegenerate,
  regenerating,
}: {
  insight: Insight | null;
  onRegenerate: () => void;
  regenerating: boolean;
}) {
  return (
    <div className="card">
      <div className="mb-4 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-brand-50 text-brand-600">
            <RobotOutlined />
          </span>
          <h2 className="text-base font-semibold">AI Insights</h2>
        </div>
        {insight && (
          <Button onClick={onRegenerate} loading={regenerating} icon={<RobotOutlined />}>
            Regenerate
          </Button>
        )}
      </div>

      {!insight ? (
        <div className="flex flex-col items-center gap-3 py-8 text-center">
          <span className="flex h-12 w-12 items-center justify-center rounded-full bg-slate-100 dark:bg-slate-800 text-xl text-slate-400">
            <RobotOutlined />
          </span>
          <div>
            <p className="font-medium text-slate-600 dark:text-slate-300">No AI insights yet</p>
            <p className="text-sm text-slate-400">
              Generate a summary, sentiment, action items and risks from this interaction&apos;s notes.
            </p>
          </div>
          <Button type="primary" icon={<RobotOutlined />} loading={regenerating} onClick={onRegenerate}>
            Generate insights
          </Button>
        </div>
      ) : (
        <div className="space-y-5">
          {insight.status === "fallback" && (
            <Alert
              type="warning"
              showIcon
              message="AI is temporarily unavailable"
              description="Showing a basic auto-summary for now. Click “Regenerate” to try the AI again."
            />
          )}

          <div className="flex items-center gap-3">
            <span className="text-sm font-medium text-slate-500">Sentiment</span>
            <Tag color={SENTIMENT_COLOR[insight.sentiment]} className="capitalize">
              {insight.sentiment}
            </Tag>
          </div>

          <div>
            <p className="mb-1 text-sm font-medium text-slate-500">Summary</p>
            <p className="leading-relaxed text-slate-800 dark:text-slate-100">{insight.summary}</p>
          </div>

          <div className="grid gap-5 md:grid-cols-2">
            <div>
              <p className="mb-2 text-sm font-medium text-slate-500">Action items</p>
              {insight.action_items.length ? (
                <ul className="space-y-2">
                  {insight.action_items.map((a, i) => (
                    <li key={i} className="flex items-start gap-2 text-sm text-slate-700 dark:text-slate-200">
                      <CheckCircleOutlined className="mt-0.5 text-green-500" />
                      {a}
                    </li>
                  ))}
                </ul>
              ) : (
                <p className="text-sm text-slate-400">No action items detected.</p>
              )}
            </div>
            <div>
              <p className="mb-2 text-sm font-medium text-slate-500">Risks &amp; blockers</p>
              {insight.risks.length ? (
                <ul className="space-y-2">
                  {insight.risks.map((r, i) => (
                    <li key={i} className="flex items-start gap-2 text-sm text-slate-700 dark:text-slate-200">
                      <WarningOutlined className="mt-0.5 text-amber-500" />
                      {r}
                    </li>
                  ))}
                </ul>
              ) : (
                <p className="text-sm text-slate-400">No risks identified.</p>
              )}
            </div>
          </div>

          {insight.status === "success" && insight.model && (
            <p className="text-xs text-slate-300">Generated by {insight.model}</p>
          )}
        </div>
      )}
    </div>
  );
}
